apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: python-app-0322
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-app-0322 
  name: python-app-0322
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: python-app-0322
    weight: 100 
